import React, { Component, Fragment } from "react";
const dummyData = {
  success: true,
  error: null,
  response: [
    {
      loc: {
        long: -73.949,
        lat: 40.745
      },
      interval: "day",
      periods: [
        {
          timestamp: 1525345200,
          validTime: "2018-05-03T07:00:00-04:00",
          dateTimeISO: "2018-05-03T07:00:00-04:00",
          maxTempC: 33,
          maxTempF: 91,
          minTempC: 22,
          minTempF: 72,
          avgTempC: 27,
          avgTempF: 81,
          tempC: null,
          tempF: null,
          pop: 19,
          precipMM: 0.51,
          precipIN: 0.02,
          iceaccum: 0,
          iceaccumMM: 0,
          iceaccumIN: 0,
          maxHumidity: 44,
          minHumidity: 14,
          humidity: 33,
          uvi: 8,
          pressureMB: 1016,
          pressureIN: 30,
          sky: 39,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 22,
          feelslikeF: 72,
          minFeelslikeC: 22,
          minFeelslikeF: 72,
          maxFeelslikeC: 32,
          maxFeelslikeF: 90,
          avgFeelslikeC: 29,
          avgFeelslikeF: 83,
          dewpointC: 8,
          dewpointF: 47,
          maxDewpointC: 14,
          maxDewpointF: 57,
          minDewpointC: 8,
          minDewpointF: 47,
          avgDewpointC: 11,
          avgDewpointF: 52,
          windDirDEG: 240,
          windDir: "WSW",
          windDirMaxDEG: 220,
          windDirMax: "SW",
          windDirMinDEG: 240,
          windDirMin: "WSW",
          windGustKTS: 25,
          windGustKPH: 46,
          windGustMPH: 29,
          windSpeedKTS: 11,
          windSpeedKPH: 20,
          windSpeedMPH: 12,
          windSpeedMaxKTS: 15,
          windSpeedMaxKPH: 28,
          windSpeedMaxMPH: 17,
          windSpeedMinKTS: 5,
          windSpeedMinKPH: 9,
          windSpeedMinMPH: 6,
          windDir80mDEG: 239,
          windDir80m: "WSW",
          windDirMax80mDEG: 220,
          windDirMax80m: "SW",
          windDirMin80mDEG: 240,
          windDirMin80m: "WSW",
          windGust80mKTS: 21,
          windGust80mKPH: 38,
          windGust80mMPH: 24,
          windSpeed80mKTS: 16,
          windSpeed80mKPH: 29,
          windSpeed80mMPH: 18,
          windSpeedMax80mKTS: 21,
          windSpeedMax80mKPH: 38,
          windSpeedMax80mMPH: 24,
          windSpeedMin80mKTS: 12,
          windSpeedMin80mKPH: 21,
          windSpeedMin80mMPH: 13,
          weather: "Partly Cloudy with Isolated Storms",
          weatherCoded: [
            {
              timestamp: 1525370400,
              wx: "S::T,S:L:RW",
              dateTimeISO: "2018-05-03T14:00:00-04:00"
            }
          ],
          weatherPrimary: "Isolated Storms",
          weatherPrimaryCoded: "S::T",
          cloudsCoded: "SC",
          icon: "pcloudyt.png",
          isDay: true,
          sunrise: 1525341046,
          sunriseISO: "2018-05-03T05:50:46-04:00",
          sunset: 1525391666,
          sunsetISO: "2018-05-03T19:54:26-04:00"
        },
        {
          timestamp: 1525431600,
          validTime: "2018-05-04T07:00:00-04:00",
          dateTimeISO: "2018-05-04T07:00:00-04:00",
          maxTempC: 30,
          maxTempF: 86,
          minTempC: 17,
          minTempF: 63,
          avgTempC: 23,
          avgTempF: 74,
          tempC: null,
          tempF: null,
          pop: 21,
          precipMM: 0.25,
          precipIN: 0.01,
          iceaccum: 0,
          iceaccumMM: 0,
          iceaccumIN: 0,
          maxHumidity: 66,
          minHumidity: 31,
          humidity: 48,
          uvi: 6,
          pressureMB: 1013,
          pressureIN: 29.91,
          sky: 70,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 22,
          feelslikeF: 72,
          minFeelslikeC: 22,
          minFeelslikeF: 72,
          maxFeelslikeC: 29,
          maxFeelslikeF: 84,
          avgFeelslikeC: 27,
          avgFeelslikeF: 80,
          dewpointC: 16,
          dewpointF: 60,
          maxDewpointC: 16,
          maxDewpointF: 60,
          minDewpointC: 14,
          minDewpointF: 57,
          avgDewpointC: 15,
          avgDewpointF: 59,
          windDirDEG: 240,
          windDir: "WSW",
          windDirMaxDEG: 220,
          windDirMax: "SW",
          windDirMinDEG: 240,
          windDirMin: "WSW",
          windGustKTS: 28,
          windGustKPH: 52,
          windGustMPH: 32,
          windSpeedKTS: 13,
          windSpeedKPH: 25,
          windSpeedMPH: 16,
          windSpeedMaxKTS: 18,
          windSpeedMaxKPH: 33,
          windSpeedMaxMPH: 21,
          windSpeedMinKTS: 6,
          windSpeedMinKPH: 11,
          windSpeedMinMPH: 7,
          windDir80mDEG: 245,
          windDir80m: "WSW",
          windDirMax80mDEG: 220,
          windDirMax80m: "SW",
          windDirMin80mDEG: 240,
          windDirMin80m: "WSW",
          windGust80mKTS: 27,
          windGust80mKPH: 51,
          windGust80mMPH: 31,
          windSpeed80mKTS: 20,
          windSpeed80mKPH: 37,
          windSpeed80mMPH: 23,
          windSpeedMax80mKTS: 27,
          windSpeedMax80mKPH: 51,
          windSpeedMax80mMPH: 31,
          windSpeedMin80mKTS: 11,
          windSpeedMin80mKPH: 20,
          windSpeedMin80mMPH: 13,
          weather: "Mostly Cloudy with Isolated Showers",
          weatherCoded: [
            {
              timestamp: 1525431600,
              wx: "S:L:RW",
              dateTimeISO: "2018-05-04T07:00:00-04:00"
            },
            {
              timestamp: 1525449600,
              wx: "S::T,S:L:RW",
              dateTimeISO: "2018-05-04T12:00:00-04:00"
            }
          ],
          weatherPrimary: "Isolated Showers",
          weatherPrimaryCoded: "S:L:RW",
          cloudsCoded: "BK",
          icon: "mcloudyr.png",
          isDay: true,
          sunrise: 1525427374,
          sunriseISO: "2018-05-04T05:49:34-04:00",
          sunset: 1525478128,
          sunsetISO: "2018-05-04T19:55:28-04:00"
        },
        {
          timestamp: 1525518000,
          validTime: "2018-05-05T07:00:00-04:00",
          dateTimeISO: "2018-05-05T07:00:00-04:00",
          maxTempC: 24,
          maxTempF: 75,
          minTempC: 15,
          minTempF: 59,
          avgTempC: 19,
          avgTempF: 66,
          tempC: null,
          tempF: null,
          pop: 24,
          precipMM: 14.11,
          precipIN: 0.56,
          iceaccum: 0,
          iceaccumMM: 0,
          iceaccumIN: 0,
          maxHumidity: 65,
          minHumidity: 39,
          humidity: 44,
          uvi: 6,
          pressureMB: 1018,
          pressureIN: 30.06,
          sky: 65,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 18,
          feelslikeF: 64,
          minFeelslikeC: 18,
          minFeelslikeF: 64,
          maxFeelslikeC: 23,
          maxFeelslikeF: 74,
          avgFeelslikeC: 21,
          avgFeelslikeF: 70,
          dewpointC: 10,
          dewpointF: 49,
          maxDewpointC: 10,
          maxDewpointF: 49,
          minDewpointC: 8,
          minDewpointF: 46,
          avgDewpointC: 8,
          avgDewpointF: 47,
          windDirDEG: 320,
          windDir: "NW",
          windDirMaxDEG: 210,
          windDirMax: "SSW",
          windDirMinDEG: 320,
          windDirMin: "NW",
          windGustKTS: 9,
          windGustKPH: 17,
          windGustMPH: 11,
          windSpeedKTS: 6,
          windSpeedKPH: 12,
          windSpeedMPH: 7,
          windSpeedMaxKTS: 8,
          windSpeedMaxKPH: 15,
          windSpeedMaxMPH: 9,
          windSpeedMinKTS: 2,
          windSpeedMinKPH: 4,
          windSpeedMinMPH: 2,
          windDir80mDEG: 326,
          windDir80m: "NW",
          windDirMax80mDEG: 210,
          windDirMax80m: "SSW",
          windDirMin80mDEG: 320,
          windDirMin80m: "NW",
          windGust80mKTS: 10,
          windGust80mKPH: 18,
          windGust80mMPH: 11,
          windSpeed80mKTS: 6,
          windSpeed80mKPH: 12,
          windSpeed80mMPH: 7,
          windSpeedMax80mKTS: 10,
          windSpeedMax80mKPH: 18,
          windSpeedMax80mMPH: 11,
          windSpeedMin80mKTS: 2,
          windSpeedMin80mKPH: 3,
          windSpeedMin80mMPH: 2,
          weather: "Partly Cloudy with Isolated Showers",
          weatherCoded: [
            {
              timestamp: 1525518000,
              wx: "S:L:RW",
              dateTimeISO: "2018-05-05T07:00:00-04:00"
            },
            {
              timestamp: 1525543200,
              wx: "S:L:RW",
              dateTimeISO: "2018-05-05T14:00:00-04:00"
            }
          ],
          weatherPrimary: "Isolated Showers",
          weatherPrimaryCoded: "S:L:RW",
          cloudsCoded: "SC",
          icon: "pcloudyr.png",
          isDay: true,
          sunrise: 1525513702,
          sunriseISO: "2018-05-05T05:48:22-04:00",
          sunset: 1525564590,
          sunsetISO: "2018-05-05T19:56:30-04:00"
        },
        {
          timestamp: 1525604400,
          validTime: "2018-05-06T07:00:00-04:00",
          dateTimeISO: "2018-05-06T07:00:00-04:00",
          maxTempC: 20,
          maxTempF: 68,
          minTempC: 12,
          minTempF: 54,
          avgTempC: 16,
          avgTempF: 61,
          tempC: null,
          tempF: null,
          pop: 37,
          precipMM: 8.41,
          precipIN: 0.33,
          iceaccum: null,
          iceaccumMM: null,
          iceaccumIN: null,
          maxHumidity: 72,
          minHumidity: 37,
          humidity: 65,
          uvi: 7,
          pressureMB: 1012,
          pressureIN: 29.88,
          sky: 73,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 16,
          feelslikeF: 60,
          minFeelslikeC: 16,
          minFeelslikeF: 60,
          maxFeelslikeC: 19,
          maxFeelslikeF: 67,
          avgFeelslikeC: 18,
          avgFeelslikeF: 64,
          dewpointC: 10,
          dewpointF: 50,
          maxDewpointC: 12,
          maxDewpointF: 53,
          minDewpointC: 10,
          minDewpointF: 50,
          avgDewpointC: 11,
          avgDewpointF: 52,
          windDirDEG: 100,
          windDir: "E",
          windDirMaxDEG: 80,
          windDirMax: "E",
          windDirMinDEG: 100,
          windDirMin: "E",
          windGustKTS: 10,
          windGustKPH: 19,
          windGustMPH: 12,
          windSpeedKTS: 3,
          windSpeedKPH: 6,
          windSpeedMPH: 4,
          windSpeedMaxKTS: 4,
          windSpeedMaxKPH: 8,
          windSpeedMaxMPH: 5,
          windSpeedMinKTS: 2,
          windSpeedMinKPH: 4,
          windSpeedMinMPH: 2,
          windDir80mDEG: 190,
          windDir80m: "S",
          windDirMax80mDEG: 80,
          windDirMax80m: "E",
          windDirMin80mDEG: 100,
          windDirMin80m: "E",
          windGust80mKTS: 15,
          windGust80mKPH: 27,
          windGust80mMPH: 17,
          windSpeed80mKTS: 11,
          windSpeed80mKPH: 20,
          windSpeed80mMPH: 12,
          windSpeedMax80mKTS: 15,
          windSpeedMax80mKPH: 27,
          windSpeedMax80mMPH: 17,
          windSpeedMin80mKTS: 7,
          windSpeedMin80mKPH: 13,
          windSpeedMin80mMPH: 8,
          weather: "Mostly Cloudy with Scattered Showers",
          weatherCoded: [
            {
              timestamp: 1525604400,
              wx: "C:L:RW",
              dateTimeISO: "2018-05-06T07:00:00-04:00"
            }
          ],
          weatherPrimary: "Scattered Showers",
          weatherPrimaryCoded: "C:L:RW",
          cloudsCoded: "BK",
          icon: "mcloudyr.png",
          isDay: true,
          sunrise: 1525600032,
          sunriseISO: "2018-05-06T05:47:12-04:00",
          sunset: 1525651051,
          sunsetISO: "2018-05-06T19:57:31-04:00"
        },
        {
          timestamp: 1525690800,
          validTime: "2018-05-07T07:00:00-04:00",
          dateTimeISO: "2018-05-07T07:00:00-04:00",
          maxTempC: 19,
          maxTempF: 66,
          minTempC: 11,
          minTempF: 52,
          avgTempC: 15,
          avgTempF: 59,
          tempC: null,
          tempF: null,
          pop: 19,
          precipMM: 0,
          precipIN: 0,
          iceaccum: null,
          iceaccumMM: null,
          iceaccumIN: null,
          maxHumidity: 75,
          minHumidity: 57,
          humidity: 56,
          uvi: 1,
          pressureMB: 1022,
          pressureIN: 30.18,
          sky: 51,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 14,
          feelslikeF: 56,
          minFeelslikeC: 13,
          minFeelslikeF: 56,
          maxFeelslikeC: 18,
          maxFeelslikeF: 65,
          avgFeelslikeC: 16,
          avgFeelslikeF: 61,
          dewpointC: 8,
          dewpointF: 46,
          maxDewpointC: 8,
          maxDewpointF: 46,
          minDewpointC: 7,
          minDewpointF: 44,
          avgDewpointC: 7,
          avgDewpointF: 45,
          windDirDEG: 360,
          windDir: "N",
          windDirMaxDEG: 160,
          windDirMax: "SSE",
          windDirMinDEG: 30,
          windDirMin: "NNE",
          windGustKTS: 12,
          windGustKPH: 23,
          windGustMPH: 14,
          windSpeedKTS: 4,
          windSpeedKPH: 7,
          windSpeedMPH: 4,
          windSpeedMaxKTS: 5,
          windSpeedMaxKPH: 9,
          windSpeedMaxMPH: 6,
          windSpeedMinKTS: 2,
          windSpeedMinKPH: 4,
          windSpeedMinMPH: 2,
          windDir80mDEG: 9,
          windDir80m: "N",
          windDirMax80mDEG: 160,
          windDirMax80m: "SSE",
          windDirMin80mDEG: 30,
          windDirMin80m: "NNE",
          windGust80mKTS: 18,
          windGust80mKPH: 33,
          windGust80mMPH: 20,
          windSpeed80mKTS: 14,
          windSpeed80mKPH: 27,
          windSpeed80mMPH: 16,
          windSpeedMax80mKTS: 18,
          windSpeedMax80mKPH: 33,
          windSpeedMax80mMPH: 20,
          windSpeedMin80mKTS: 11,
          windSpeedMin80mKPH: 21,
          windSpeedMin80mMPH: 13,
          weather: "Partly Cloudy with Isolated Showers",
          weatherCoded: [
            {
              timestamp: 1525690800,
              wx: "S:L:RW",
              dateTimeISO: "2018-05-07T07:00:00-04:00"
            }
          ],
          weatherPrimary: "Isolated Showers",
          weatherPrimaryCoded: "S:L:RW",
          cloudsCoded: "SC",
          icon: "pcloudyr.png",
          isDay: true,
          sunrise: 1525686364,
          sunriseISO: "2018-05-07T05:46:04-04:00",
          sunset: 1525737513,
          sunsetISO: "2018-05-07T19:58:33-04:00"
        },
        {
          timestamp: 1525777200,
          validTime: "2018-05-08T07:00:00-04:00",
          dateTimeISO: "2018-05-08T07:00:00-04:00",
          maxTempC: 21,
          maxTempF: 69,
          minTempC: 12,
          minTempF: 54,
          avgTempC: 16,
          avgTempF: 61,
          tempC: null,
          tempF: null,
          pop: 7,
          precipMM: 0,
          precipIN: 0,
          iceaccum: null,
          iceaccumMM: null,
          iceaccumIN: null,
          maxHumidity: 66,
          minHumidity: 47,
          humidity: 47,
          uvi: null,
          pressureMB: 1027,
          pressureIN: 30.33,
          sky: 26,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 14,
          feelslikeF: 56,
          minFeelslikeC: 14,
          minFeelslikeF: 56,
          maxFeelslikeC: 20,
          maxFeelslikeF: 68,
          avgFeelslikeC: 17,
          avgFeelslikeF: 63,
          dewpointC: 5,
          dewpointF: 42,
          maxDewpointC: 6,
          maxDewpointF: 43,
          minDewpointC: 5,
          minDewpointF: 42,
          avgDewpointC: 6,
          avgDewpointF: 42,
          windDirDEG: 270,
          windDir: "W",
          windDirMaxDEG: 190,
          windDirMax: "S",
          windDirMinDEG: 270,
          windDirMin: "W",
          windGustKTS: 6,
          windGustKPH: 11,
          windGustMPH: 7,
          windSpeedKTS: 4,
          windSpeedKPH: 7,
          windSpeedMPH: 4,
          windSpeedMaxKTS: 5,
          windSpeedMaxKPH: 9,
          windSpeedMaxMPH: 6,
          windSpeedMinKTS: 3,
          windSpeedMinKPH: 5,
          windSpeedMinMPH: 3,
          windDir80mDEG: 2,
          windDir80m: "N",
          windDirMax80mDEG: 190,
          windDirMax80m: "S",
          windDirMin80mDEG: 270,
          windDirMin80m: "W",
          windGust80mKTS: 7,
          windGust80mKPH: 13,
          windGust80mMPH: 8,
          windSpeed80mKTS: 4,
          windSpeed80mKPH: 7,
          windSpeed80mMPH: 4,
          windSpeedMax80mKTS: 7,
          windSpeedMax80mKPH: 13,
          windSpeedMax80mMPH: 8,
          windSpeedMin80mKTS: 2,
          windSpeedMin80mKPH: 4,
          windSpeedMin80mMPH: 3,
          weather: "Mostly Sunny",
          weatherCoded: [],
          weatherPrimary: "Mostly Sunny",
          weatherPrimaryCoded: "::FW",
          cloudsCoded: "FW",
          icon: "pcloudy.png",
          isDay: true,
          sunrise: 1525772696,
          sunriseISO: "2018-05-08T05:44:56-04:00",
          sunset: 1525823974,
          sunsetISO: "2018-05-08T19:59:34-04:00"
        },
        {
          timestamp: 1525863600,
          validTime: "2018-05-09T07:00:00-04:00",
          dateTimeISO: "2018-05-09T07:00:00-04:00",
          maxTempC: 22,
          maxTempF: 71,
          minTempC: 14,
          minTempF: 58,
          avgTempC: 18,
          avgTempF: 65,
          tempC: null,
          tempF: null,
          pop: 9,
          precipMM: 0,
          precipIN: 0,
          iceaccum: null,
          iceaccumMM: null,
          iceaccumIN: null,
          maxHumidity: 69,
          minHumidity: 37,
          humidity: 51,
          uvi: null,
          pressureMB: 1023,
          pressureIN: 30.21,
          sky: 20,
          snowCM: 0,
          snowIN: 0,
          feelslikeC: 14,
          feelslikeF: 58,
          minFeelslikeC: 14,
          minFeelslikeF: 58,
          maxFeelslikeC: 21,
          maxFeelslikeF: 69,
          avgFeelslikeC: 18,
          avgFeelslikeF: 64,
          dewpointC: 7,
          dewpointF: 45,
          maxDewpointC: 8,
          maxDewpointF: 46,
          minDewpointC: 7,
          minDewpointF: 45,
          avgDewpointC: 7,
          avgDewpointF: 45,
          windDirDEG: 350,
          windDir: "N",
          windDirMaxDEG: 140,
          windDirMax: "SE",
          windDirMinDEG: 350,
          windDirMin: "N",
          windGustKTS: 8,
          windGustKPH: 15,
          windGustMPH: 10,
          windSpeedKTS: 5,
          windSpeedKPH: 10,
          windSpeedMPH: 6,
          windSpeedMaxKTS: 6,
          windSpeedMaxKPH: 11,
          windSpeedMaxMPH: 7,
          windSpeedMinKTS: 2,
          windSpeedMinKPH: 4,
          windSpeedMinMPH: 3,
          windDir80mDEG: 21,
          windDir80m: "NNE",
          windDirMax80mDEG: 140,
          windDirMax80m: "SE",
          windDirMin80mDEG: 350,
          windDirMin80m: "N",
          windGust80mKTS: 10,
          windGust80mKPH: 19,
          windGust80mMPH: 12,
          windSpeed80mKTS: 7,
          windSpeed80mKPH: 13,
          windSpeed80mMPH: 8,
          windSpeedMax80mKTS: 10,
          windSpeedMax80mKPH: 19,
          windSpeedMax80mMPH: 12,
          windSpeedMin80mKTS: 5,
          windSpeedMin80mKPH: 9,
          windSpeedMin80mMPH: 6,
          weather: "Mostly Sunny",
          weatherCoded: [],
          weatherPrimary: "Mostly Sunny",
          weatherPrimaryCoded: "::FW",
          cloudsCoded: "FW",
          icon: "pcloudy.png",
          isDay: true,
          sunrise: 1525859031,
          sunriseISO: "2018-05-09T05:43:51-04:00",
          sunset: 1525910434,
          sunsetISO: "2018-05-09T20:00:34-04:00"
        }
      ],
      profile: {
        tz: "America/New_York"
      }
    }
  ]
};

console.log(dummyData.response[0].periods);

class SingleDay extends Component {
  constructor(props) {
    super(props);

    this.state = {
      jsonData: "",
      currentMeasurement: "Celsius",
      currentShort: "C",
      currentDate: "",
      currentLogo: "",
      highTempC: "",
      lowTempC: "",
      highTempF: "",
      lowTempF: "",
    };

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(event) {
    let { currentMeasurement } = this.state;
    if (currentMeasurement === "Celsius") {
      this.setState({
        currentMeasurement: "Farenheit",
        currentShort: "F",
      });
    } else {
      this.setState({
        currentMeasurement: "Celsius",
        currentShort: "C",
      });
    }
  }

  render() {
    let sevenDayForecast = dummyData.response[0].periods;
    let { currentMeasurement, currentShort } = this.state;

    return (
      <Fragment>
        <button onClick={this.handleClick}>
          Toggle from {currentMeasurement}
        </button>

        <ul className="container">
          {
            currentShort === "C"
            ? sevenDayForecast.map(data => {
                return (
                  <li className="weather-card" key={data.timestamp}>
                    <div>Date: {data.dateTimeISO.slice(0, 10)}</div>
                    <div>
                      High Temp: {data.maxTempC}º{currentShort}
                    </div>
                    <div>
                      Low Temp: {data.minTempC}º{currentShort}
                    </div>
                    <img
                      src={`/icons/${data.icon}`}
                      alt={data.weatherPrimary}
                      height="55px"
                      width="55px"
                    />
                  </li>
                );
              })
            : sevenDayForecast.map(data => {
              return (
                <li className="weather-card" key={data.timestamp}>
                  <div>Date: {data.dateTimeISO.slice(0, 10)}</div>
                  <div>
                    High Temp: {data.maxTempF}º{currentShort}
                  </div>
                  <div>
                    Low Temp: {data.minTempF}º{currentShort}
                  </div>
                  <img
                    src={`/icons/${data.icon}`}
                    alt={data.weatherPrimary}
                    height="55px"
                    width="55px"
                  />

                </li>
              );
            })
          }
        </ul>
      </Fragment>
    );
  }
}

export default SingleDay;
